# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19toESHCRytu7wMKdbETzE6aGwEELn-82
"""

a = [0,1]
permut = []

for i in a :
  for j in a:
    permut.append([i,j])

print(permut)

def orGate(arrayTwoOpt) :
  #print(arrayTwoOpt[0][0],arrayTwoOpt[0][1])
  #print()
  #print(arrayTwoOpt[1][0],arrayTwoOpt[1][1])
  #print()
  #print(arrayTwoOpt[0][2],arrayTwoOpt[1][2])
  
  
  for i in range(0,len(arrayTwoOpt)-2):
    for j in range(0,len(arrayTwoOpt)-2):
      # print(i,j)
      if(i or j == 1):
        z = 1
      else:
        z = 0
      print(z)

    
  

orGate(permut)